### ISSUE TITLE
local cache not restored

### ISSUE THREAD

**Issue by uraoul** [jonasbb/podman-gitlab-runner#17]
It looks like cache isn't working as expected with gitlab-runner custom executor to podman.

With the following .gitlab-ci.yml (that works with a plain docker executor), Job B fails because `cat` command  cannot find `hello.txt` file that sould have been restored from cache. 

```yaml
default:
  image: debian:buster
  tags:
    - podman

stages:
  - build
  - test

job A:
  stage: build
  script:
    - mkdir -p vendor/
    - echo "build" > vendor/hello.txt
  cache:
    key: build-cache
    paths:
      - vendor/

job B:
  stage: test
  script:
    - cat vendor/hello.txt
  cache:
    key: build-cache
    paths:                                                                                                            
      - vendor/
    policy: pull
```
Here is (part of) my `config.toml`

```toml
[[runners]]
  name = "pleiades-ci podman runner"
  url = "https://[masked]"
  token = "[masked]"
  executor = "custom"
  builds_dir = "/builds"
  cache_dir = "/cache"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.custom]

    prepare_exec = "/home/me/bin2/prepare.sh"
    prepare_exec_timeout = 1800

    run_exec = "/home/me/bin2/run.sh"

    cleanup_exec = "/home/me/bin2/cleanup.sh"
    cleanup_exec_timeout = 300

    graceful_kill_timeout = 60
    force_kill_timeout = 180
```

Here is the output of the failling job :

```text
Setting up git-lfs (2.7.1-1+deb10u1) ...
Preparing environment 00:00
Running on 7a72d7ad609c...
Getting source from Git repository 00:01
Fetching changes with git depth set to 50...
Initialized empty Git repository in /builds/DEC/pleiades/demo-ci-cd/.git/
Created fresh repository.
Checking out 5c308f92 as test-cache-podman...
Skipping Git submodules setup
Restoring cache 00:00
Checking cache for build-cache...
Runtime platform                                    arch=amd64 os=linux pid=3635 revision=58ba2b95 version=14.2.0
No URL provided, cache will not be downloaded from shared cache server. Instead a local version of cache will be extracted. 
Successfully extracted cache
Executing "step_script" stage of the job script 00:00
WARNING: Starting with version 14.0 the 'build_script' stage will be replaced with 'step_script': https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26426
$ cat vendor/hello.txt
cat: vendor/hello.txt: No such file or directory
Cleaning up file based variables 00:01
ERROR: Job failed: exit status 1
```

Am i missing something ?
